### ISSUE TITLE
Error: Failed to install ffmpeg

### ISSUE THREAD

**Issue by Supervinh** [charmbracelet/vhs-action#459]
### Describe the bug

The action fails to install ffmpeg, exiting with an error.

<details><summary>Click to see debug log output</summary>

```
Run charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3
Installing default fonts...
Installing JetBrainsMono
Downloading JetBrainsMono
/usr/bin/unzip -o -q /home/runner/work/_temp/ffc9fe4a-df69-497e-87c9-b88c36c41a4a
Installing JetBrainsMono-nerd
Downloading JetBrainsMono-nerd
/usr/bin/unzip -o -q /home/runner/work/_temp/85c39195-f207-4f49-80c4-33608ec8927d
/usr/bin/fc-cache -f -v
Font directories:
	/home/runner/.local/share/fonts
	/usr/local/share/fonts
	/usr/share/fonts
	/home/runner/.fonts
	/usr/share/fonts/truetype
	/usr/share/fonts/truetype/dejavu
	/usr/share/fonts/truetype/lato
	/usr/share/fonts/truetype/liberation
	/usr/share/fonts/truetype/noto
/home/runner/.local/share/fonts: caching, new cache contents: 128 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 4 dirs
/usr/share/fonts/truetype/dejavu: caching, new cache contents: 22 fonts, 0 dirs
/usr/share/fonts/truetype/lato: caching, new cache contents: 18 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/truetype/noto: caching, new cache contents: 1 fonts, 0 dirs
/home/runner/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/dejavu: skipping, looped directory detected
/usr/share/fonts/truetype/lato: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/noto: skipping, looped directory detected
/var/cache/fontconfig: not cleaning unwritable cache directory
/home/runner/.cache/fontconfig: cleaning cache directory
/home/runner/.fontconfig: not cleaning non-existent cache directory
/usr/bin/fc-cache: succeeded
Installing dependencies...
Installing ttyd latest...
Installing latest ffmpeg...
Error: Failed to install ffmpeg
```

</details>

### Setup

Please complete the following information along with version numbers, if applicable.
- VHS version 2.1.0
- GitHub hosted runner:

```
runs-on: ubuntu-latest
uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3
```

### To Reproduce

- Run action on GitHub hosted Ubuntu runner with the latest action version
- See error

### Source Code

```yml
name: 🎯 Test & release

on:
  push:
    branches: [main, develop]

jobs:
  test-release:
    name: 🎯 Test & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: charmbracelet/vhs-action@59641cdc7fadf3978db65eb8c6937ea2752f4ec3
        with:
          path: 'vhs.tape'
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "feat: Update generated VHS WEBM"
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.webm'
```

### Expected behavior

Install ffmpeg, generate the vhs and push it on the repository
